AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: micronaut report function
Resources:
  MicronautReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: micronaut-report-function
      Handler: br.com.fbourguignon.FunctionRequestHandler
      Description: For AWS Sqs Queue
      Runtime: java17
      MemorySize: 1024
      Timeout: 120
      Environment:
        Variables:
          MICRONAUT_ENVIROMENTS: local
          AWS_ACCESS_KEY_ID: YOUR_AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY