micronaut:
  application:
    name: micronautReportFunction
email:
  sender:
    from: 'company@gmail.com'
jpa:
  default:
    packages-to-scan:
      - 'br.com.fbourguignon'
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://db:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    schema-generate: UPDATE
    dialect: POSTGRES
    allow-pool-suspension: true
jpa.default.properties.hibernate.hbm2ddl.auto: update